name: .NET Core

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.207
    
    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --no-build --no-restore --verbosity normal

    - name: Generate package
      run: dotnet pack --no-build --configuration Release -o out
      
    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./<project>/out/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate --no-symbols true
